spring:
  jpa:
    database: POSTGRESQL
    show-sql: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/transportation
    username: postgres
    password: 4488

  database:
    driverClassName: org.postgresql.Driver

server:
  port: 4222

